name: Bug Report
description: Report a bug in FOSSManualPayment for FOSSBilling
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: fossbilling-version
    attributes:
      label: FOSSBilling Version
      description: What version of FOSSBilling are you running?
      options:
        - "Latest"
        - "Other (specify below)"
    validations:
      required: true

  - type: input
    id: fossbilling-version-other
    attributes:
      label: FOSSBilling Version (Other)
      description: Specify your FOSSBilling version if not 'Latest'
      placeholder: "e.g., 0.x.x"
    validations:
      required: false

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you running?
      placeholder: "e.g., 8.1"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: FOSSManualPayment Version
      description: What version of FOSSManualPayment are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and how to reproduce it
      placeholder: |
        1. Go to payment gateway configuration...
        2. Set up the following...
        3. Try to process a payment...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: html-configuration
    attributes:
      label: Custom HTML Configuration
      description: Please provide your custom HTML configuration
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant error logs from your server
      render: shell