name: Question
description: Ask a question about FOSSManualPayment
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: "Thanks for your interest in FOSSManualPayment!"

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know about FOSSManualPayment?
      placeholder: Please be as specific as possible
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - "Installation"
        - "Configuration"
        - "Other"
    validations:
      required: true
